### ISSUE TITLE
Video/MP4 Upload...

### ISSUE THREAD

**Issue by doug62** [mozmorris/react-webcam#212]
Is it possible to capture a movie with sound and post to server? (thanks)

**Comment by mozmorris** [comment]
It is possible, yes. Take a look at https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

In the case of the `<Webcam />` component, one can get access to the stream via ref to the component eg `componentRef.current.stream`

**Comment by theMitch36** [comment]
Could you provide an example of this?
 
I have followed the mozilla developer guide and keep getting the error "Failed to execute 'start' on 'MediaRecorder': The MediaRecorder cannot start because there are no audio or video tracks available."
 
When i try to use componentRef.stream it comes back undefined and so i created a new MediaRecorder using componentRef.video and i get an inactive MediaRecorder that cant start. 

I also looked into issue #30 and cant get it to work.

Any help would be greatly appreciated!

**Comment by mozmorris** [comment]
@theMitch36 this is a recurring theme, so I'll try to create an example.

**Comment by theMitch36** [comment]
@mozmorris Thank you!

**Comment by mozmorris** [comment]
@theMitch36 here's an example: https://codepen.io/mozmorris/pen/yLYKzyp?editors=0011

In this example I'm downloading the resulting video, but you could instead upload the resulting blob to your backend.

**Comment by theMitch36** [comment]
@mozmorris you're the best, thank you!

**Comment by mozmorris** [comment]
My pleasure 👍
