### ISSUE TITLE
Is there a way to get EXIF data?

### ISSUE THREAD

**Issue by DsEsteban** [mozmorris/react-webcam#245]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [ ] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:

If you can provide a minimal reproducible demo (CodePen, CodeSandbox, etc) or a GitHub repository, that will greatly help us to solve your problem. Many of the issues posted are questions about react-webcam usage. We don't discourage you posting a question, it's just a lot easier to help you if we can see your code.

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by mozmorris** [comment]
@DsEsteban good question. If you're referring to the capturing a screenshot, the short answer is no, unfortunately. This is because we draw the stream to canvas before returning the base64 string (the canvas step ignores any extra data)

However, my understanding is the stream itself may contain extra data and the newer api `takePhoto()` may support it.

**Comment by mozmorris** [comment]
@DsEsteban I am closing this since it's not currently supported.
