### ISSUE TITLE
Invalid SSL in Demo

### ISSUE THREAD

**Issue by Shaked** [mozmorris/react-webcam#66]
Hey

Seems like the [demo](https://www.mozmorris.com/react-webcam/examples/)'s SSL is not valid:

![privacy error 2017-12-11 19-42-32](https://user-images.githubusercontent.com/960015/33845251-7fcf3c92-deab-11e7-93dc-decb83d66d48.png)

**Comment by schroedingerscode** [comment]
Looks like the cert is a GitHub cert which is being used on the www.mozmorris.com domain. 

Presented Cert's Subject:
    CN = www.github.com
    O = "GitHub, Inc."
    L = San Francisco
    ST = California
    C = US

Presented Cert's SANs:
    DNS Name: www.github.com
    DNS Name: *.github.com 
    DNS Name: github.com
    DNS Name: *.github.io
    DNS Name: github.io
    DNS Name: *.githubusercontent.com
    DNS Name: githubusercontent.com

This would be a pretty easy fix for whoever maintans the demo at www.mozmorris.com. A simple DV cert from Let's Encrypt and 5 minutes of configuration will solve this, but it's NOT CRITICAL. Some sort of TLS is necessary because some browser don't allow accessing the getMediaStream API from non-TLS connections, but it's not like any information is actually being sent to the server.
